spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    database: h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
