# LOGGING
logging:
  level:
    root: INFO
# SPRING
spring:
  sql:
    init:
      mode: always
#  SECURITY
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  # MAIL SENDER
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: false
    database: postgresql
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}admin
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
# APPLICATION
application:
  # JWT
  security:
    jwt:
      access:
        secret-key: ${JWT_ACCESS_SECRET}
        expiration-minutes: 30
      refresh:
        secret-key: ${JWT_REFRESH_SECRET}
        expiration-days: 7
