# LOGGING
logging:
  level:
    root: INFO
# SPRING
spring:
  h2:
    console.enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    #H2 Database
    url: jdbc:h2:mem:addbazar
    username: sa
    password: password
    driverClassName: org.h2.Driver
# APPLICATION
application:
  # JWT
  security:
    jwt:
      access:
        secret-key: ${JWT_ACCESS_SECRET}
        expiration-minutes: 15
      refresh:
        secret-key: ${JWT_REFRESH_SECRET}
        expiration-days: 7
